name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile Resource and C++ Code
      run: |
        windres resource.rc -O coff -o resource.o
        g++ main.cpp resource.o -o output.exe

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: MyProgram
        path: output.exe
